# Naive Bayes 
## Mini Example
Using `scikit-learn` library we will build a *Naive Bayes* model. Under this library there are three types of Naive Bayes models:

+ Gaussian: It is used in classification and it assumes that features follow a normal distribution.
+ Multinomial: It is used for discrete counts. For example, let’s say,  we have a text classification problem. Here we can consider bernoulli trials which is one step further and instead of “word occurring in the document”, we have “count how often word occurs in the document”, you can think of it as “number of times outcome number x_i is observed over the n trials”.
+ Bernoulli: The binomial model is useful if your feature vectors are binary (i.e. zeros and ones). One application would be text classification with ‘bag of words’ model where the 1s & 0s are “word occurs in the document” and “word does not occur in the document” respectively.

Based on your data set, you can choose any of above discussed model. Below is the example of Gaussian model.

In [4]:
#Import Library of Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
import numpy as np

# The following piece of code gives the opportunity to show multiple outputs
# in one cell:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
#assigning predictor and target variables
x= np.array([[-3,7],[1,5], [1,2], [-2,0], [2,3], [-4,0], [-1,1], [1,1], [-2,2], [2,7], [-4,1], [-2,7]])
Y = np.array([3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 4])
x
Y

array([[-3,  7],
       [ 1,  5],
       [ 1,  2],
       [-2,  0],
       [ 2,  3],
       [-4,  0],
       [-1,  1],
       [ 1,  1],
       [-2,  2],
       [ 2,  7],
       [-4,  1],
       [-2,  7]])

array([3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 4])

In [6]:
#Create a Gaussian Classifier
model = GaussianNB()

In [8]:
# Train the model using the training sets 
model.fit(x, Y)

GaussianNB(priors=None)

In [9]:
# Predict Output for [1,2] and [3,4] 
predicted= model.predict([[1,2],[3,4]])
print (predicted)

[3 4]


In [12]:
# Predict output of the training set 
model.predict(x)

array([4, 4, 3, 3, 4, 3, 3, 3, 3, 4, 3, 4])

In [15]:
# Train set performance (Accuracy)
model.score(x, Y)

0.6666666666666666